/*
 * events.h
 *
 *  Created on: Apr 25, 2024
 *      Author: Tyuryakov_OA
 */

#ifndef INC_EVENTS_H_
#define INC_EVENTS_H_

/**************type declaration****************/
typedef enum{
	BUTTONS_NONE_PRESSED,
	BUTTON_OK_SHORT_PRESSED,
	BUTTON_OK_LONG_PRESSED,
	BUTTON_OK_VERY_LONG_PRESSED,
	BUTTON_UP_SHORT_PRESSED,
	BUTTON_UP_LONG_PRESSED = 8,
	BUTTON_UP_VERY_LONG_PRESSED = 12,
	BUTTON_DOWN_SHORT_PRESSED = 16,
	BUTTON_DOWN_LONG_PRESSED = 32,
	BUTTON_DOWN_VERY_LONG_PRESSED = 48,
	BUTTON_RIGHT_SHORT_PRESSED = 64,
	BUTTON_RIGHT_LONG_PRESSED = 128,
	BUTTON_RIGHT_VERY_LONG_PRESSED = 192,
	BUTTON_LEFT_SHORT_PRESSED = 256,
	BUTTON_LEFT_LONG_PRESSED = 512,
	BUTTON_LEFT_VERY_LONG_PRESSED = 768
} eEvents_t;


/****************Function declaration****************/
#endif /* INC_EVENTS_H_ */
